### ISSUE TITLE
Registration checklist

### ISSUE THREAD

**Issue by charleskawczynski** [charleskawczynski/TexasHoldem.jl#97]
I think it's nearly time to register, but there are still a few things that need to be addressed:

 - [ ] Documentation
 - [ ] First sketch of API
 - [x] Should we change the interface (`TH.player_option!(game::Game, player::Player{BotCheckFold}, ::AbstractGameState, ::CheckRaiseFold)`) to exclude `AbstractGameState`?
 - [x] Take one more pass at profiling.
 - [x] Add "silent" (maybe available through logger?) mode for downstream training

**Comment by charleskawczynski** [comment]
Since the docs depend on the API, and I think that the API may take a fair bit of time to converge, I think it's fine to register with v0.1.0 now.
